workers_dev = true

name = "my-react-router-worker"
compatibility_date = "2024-11-18"
main = "./build/server/static/js/app.js"
assets = { directory = "./build/client/" }

[build]
#command = "npm run build"
#watch_dir = "app"

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
